name: Build and Release

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write # Required to create a release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build application
        run: build.bat
        shell: cmd

      - name: Determine Release Properties
        id: release_props
        shell: pwsh
        run: |
          $csproj_path = "${{ github.workspace }}\src\BooTools.UI\BooTools.UI.csproj"
          $csproj_content = Get-Content $csproj_path -Raw
          [xml]$csproj_xml = $csproj_content
          $version = $csproj_xml.Project.PropertyGroup.Version

          if (-not $version) {
            echo "Error: Version tag not found in $csproj_path"
            exit 1
          }

          $is_prerelease = $false
          $tag_name = "v$version"
          $release_name = "Release v$version"

          if ("${{ github.ref }}" -eq "refs/heads/dev") {
            $is_prerelease = $true
            $build_date = (Get-Date -Format 'yyyyMMdd-HHmmss')
            $tag_name = "v$version-dev-$build_date"
            $release_name = "Pre-release v$version (dev)"
          }

          echo "is_prerelease=$is_prerelease" >> $env:GITHUB_OUTPUT
          echo "tag_name=$tag_name" >> $env:GITHUB_OUTPUT
          echo "release_name=$release_name" >> $env:GITHUB_OUTPUT

      - name: Package Artifacts
        id: package
        shell: pwsh
        run: |
          $artifact_dir = "${{ github.workspace }}\src\BooTools.UI\bin\Release\net8.0-windows"
          $zip_path = "${{ github.workspace }}\boo-tools-release.zip"
          Compress-Archive -Path "$artifact_dir\*" -DestinationPath $zip_path -Force
          echo "zip_path=$zip_path" >> $env:GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_props.outputs.tag_name }}
          release_name: ${{ steps.release_props.outputs.release_name }}
          draft: false
          prerelease: ${{ steps.release_props.outputs.is_prerelease }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.package.outputs.zip_path }}
          asset_name: boo-tools-release.zip
          asset_content_type: application/zip
