# BooTools Build Workflow
name: Build BooTools

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Build and Assemble
      run: |
        powershell -ExecutionPolicy Bypass -File build\BuildAndAssemble.ps1 -Configuration Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BooTools-Build
        path: bin/